import { canonicalJson, deepFreeze, sha256 } from "./canonical";
import { basisPoints as bps, cents } from "./money";
import type { PricingCatalog } from "./types";

const catalogPayload = {
  code: "MERCURIUS_MASTER_PRICING",
  version: "2026-06-30",
  status: "active",
  effectiveFrom: "2026-06-30",
  currency: "USD",
  sourceDocument: "Mercurius Pricing Reference Sheet - 2026-06-30",
  cores: [
    {
      code: "FREE",
      name: "Free",
      setupCents: cents(0),
      monthlyCents: cents(0),
      customPricing: false,
      baseCommissionBps: bps(1_500),
      floorCommissionBps: bps(1_500),
      sortOrder: 0,
    },
    {
      code: "SPARK",
      name: "Spark",
      setupCents: cents(99_900),
      monthlyCents: cents(9_900),
      customPricing: false,
      baseCommissionBps: bps(1_200),
      floorCommissionBps: bps(600),
      sortOrder: 1,
    },
    {
      code: "SPARK_PRO",
      name: "Spark Pro",
      setupCents: cents(150_000),
      monthlyCents: cents(39_900),
      customPricing: false,
      baseCommissionBps: bps(1_000),
      floorCommissionBps: bps(550),
      sortOrder: 2,
    },
    {
      code: "INSIGHT",
      name: "Insight",
      setupCents: cents(250_000),
      monthlyCents: cents(59_900),
      customPricing: false,
      baseCommissionBps: bps(800),
      floorCommissionBps: bps(500),
      sortOrder: 3,
    },
    {
      code: "INTELLIGENCE",
      name: "Intelligence",
      setupCents: cents(450_000),
      monthlyCents: cents(99_900),
      customPricing: false,
      baseCommissionBps: bps(600),
      floorCommissionBps: bps(400),
      sortOrder: 4,
    },
    {
      code: "INTELLIGENCE_PRO",
      name: "Intelligence Pro",
      setupCents: cents(650_000),
      monthlyCents: cents(149_900),
      customPricing: false,
      baseCommissionBps: bps(450),
      floorCommissionBps: bps(350),
      sortOrder: 5,
    },
    {
      code: "NEXUS",
      name: "Nexus",
      setupCents: null,
      monthlyCents: null,
      customPricing: true,
      baseCommissionBps: null,
      floorCommissionBps: null,
      sortOrder: 6,
    },
  ],
  enhancements: [
    {
      code: "AI_MARKETING_COPILOT",
      name: "AI Marketing Co-Pilot",
      classification: "software",
      monthlyCents: cents(14_900),
      sortOrder: 0,
    },
    {
      code: "VISIBILITY_ACCELERATOR",
      name: "Visibility Accelerator",
      classification: "software",
      monthlyCents: cents(17_900),
      sortOrder: 1,
    },
    {
      code: "RETENTION_ENGINE",
      name: "Retention Engine",
      classification: "software",
      monthlyCents: cents(17_900),
      sortOrder: 2,
    },
    {
      code: "LEAD_VELOCITY",
      name: "Lead Velocity",
      classification: "software",
      monthlyCents: cents(24_900),
      sortOrder: 3,
    },
    {
      code: "SOCIAL_COMMAND",
      name: "Social Command",
      classification: "service",
      monthlyCents: cents(29_900),
      sortOrder: 4,
    },
    {
      code: "VIDEO_VELOCITY",
      name: "Video Velocity",
      classification: "service",
      monthlyCents: cents(59_700),
      sortOrder: 5,
    },
    {
      code: "CONTENT_COMMAND_SUITE",
      name: "Content Command Suite",
      classification: "service",
      monthlyCents: cents(79_700),
      sortOrder: 6,
    },
    {
      code: "ADS_COMMAND",
      name: "Ads Command",
      classification: "ads",
      monthlyCents: cents(149_700),
      sortOrder: 7,
    },
  ],
  tierRules: [
    { coreCode: "FREE", softwareBps: bps(0), serviceCapBps: bps(0) },
    { coreCode: "SPARK", softwareBps: bps(500), serviceCapBps: bps(1_000) },
    { coreCode: "SPARK_PRO", softwareBps: bps(1_000), serviceCapBps: bps(1_000) },
    { coreCode: "INSIGHT", softwareBps: bps(1_200), serviceCapBps: bps(1_000) },
    { coreCode: "INTELLIGENCE", softwareBps: bps(1_800), serviceCapBps: bps(1_200) },
    { coreCode: "INTELLIGENCE_PRO", softwareBps: bps(2_000), serviceCapBps: bps(1_500) },
    { coreCode: "NEXUS", softwareBps: null, serviceCapBps: null },
  ],
  bundleRules: [
    { minimumCount: 0, discountBps: bps(0) },
    { minimumCount: 2, discountBps: bps(1_000) },
    { minimumCount: 3, discountBps: bps(1_500) },
    { minimumCount: 4, discountBps: bps(2_000) },
  ],
  policies: {
    maxLineDiscountBps: bps(3_800),
    upfrontCommissionBps: bps(2_500),
    residualBps: bps(1_000),
    adsCountsForBundle: false,
    adSpendCommissionable: false,
    roundingMode: "HALF_UP_PER_LINE",
    residualStartsMonth: 2,
    yearOneResidualPayments: 12,
  },
} as const satisfies Omit<PricingCatalog, "checksum" | "checksumAlgorithm">;

export const PRICING_2026_06_30: PricingCatalog = deepFreeze({
  ...catalogPayload,
  checksumAlgorithm: "SHA-256",
  checksum: sha256(canonicalJson(catalogPayload)),
});
